### ISSUE TITLE
测试配置-全局配置，类型为String而且字符串超长时，页面字符串溢出

### ISSUE THREAD

**Issue by ohmydengzi** [wuranxu/pityWeb#13]
问题：测试配置-全局配置，类型为String而且字符串超长时，页面字符串溢出
图片：如下图
![image](https://github.com/wuranxu/pityWeb/assets/13642149/21eab208-b995-40c0-94b4-3f1e2435397d)

**Comment by wuranxu** [comment]
[column api](https://ant.design/components/table-cn#column)

![image](https://github.com/wuranxu/pityWeb/assets/11266738/c784ecd0-c625-46b9-9401-0bfc2f423a77)
