### ISSUE TITLE
build failed.ERROR in ./src/models/user.js

### ISSUE THREAD

**Issue by mijiawei** [wuranxu/pityWeb#3]
This dependency was not found:

* _querystring@0.2.1@querystring in ./src/models/user.js

To install it, you can run: npm install --save _querystring@0.2.1@querystring
Child
    
    ERROR in ./src/models/user.js
    Module not found: Error: Can't resolve '_querystring@0.2.1@querystring' in '/Users/sh98024ml/pityWeb/src/models'
     @ ./src/models/user.js 9:0-59
     @ ./src/.umi-production/plugin-dva/dva.ts
     @ ./src/.umi-production/plugin-dva/exports.ts
     @ ./src/.umi-production/core/umiExports.ts
     @ ./node_modules/umi/dist/index.esm.js
     @ ./src/global.jsx
     @ ./src/.umi-production/umi.ts
     @ multi ./src/.umi-production/umi.ts
null
build failed

**Comment by wuranxu** [comment]
去models/user.js把_querystring@0.2.1@querystring 改为querystring, 或者拉最新代码。
