### ISSUE TITLE
npm run start 登录页报错

### ISSUE THREAD

**Issue by Vicxiaoyezi** [wuranxu/pityWeb#5]
报错信息 antd_es_form__WEBPACK_IMPORTED_MODULEantd_es_form__WEBPACK_IMPORTED_MODULE_10__.default.useFormInstance is not a function

fix
package.json 升级 "antd": "^4.20.0",

**Comment by Vicxiaoyezi** [comment]
固定3.5.22依然报错的，还是需要升级"antd": "^4.20.0",

**Comment by wuranxu** [comment]
> 固定3.5.22依然报错的，还是需要升级"antd": "^4.20.0",

> 虽然可以通过升级antd解决，但是代码都是基于antd4.17.0的，不保证antd的更新会不会产生bug。

1. git clone项目
2. 将所有npm包版本都固定
3. npm install （如果期间报dependency tree问题，需要npm install -f，不建议cnpm安装）
4. npm run start

**如果已经有项目了，删除node_modules目录重新按照2-4步骤操作。如果Windows提示node_modules被占用，无法删除，简单点可以重启再删除，也可用rimraf包删除。**

**Comment by leo-qa** [comment]
终于可以了，连续试错了近3个小时，正确方式应该是：把这个升级"antd": "^4.20.0",  然后umi版本号固定，去掉^这个了，
重新npm install -f  即可。
