### ISSUE TITLE
前端本地部署完后，启动部分会报错

### ISSUE THREAD

**Issue by leo-qa** [wuranxu/pityWeb#7]
**遇到两个问题，如果直接安装依赖，这样启动直接报错，所以先要把package.json里的umi设置成"umi": "3.5.22" ，然后会遇到如下问题：**
1、遇到这个问题，"umi": "3.5.22"和"antd": "^4.17.0" 的时候，安装依赖npm install -f ， 启动后，这个菜单下的页面就报错。
![f756e7e26b7c070cd23b44cc9fe7e02](https://user-images.githubusercontent.com/35160325/200168017-df96d636-ca44-433c-894e-70d7973045fc.png)

2、 如果把antd这个升级到4.20.0的话， 实用工具里面的页面可以正常显示和使用，但是测试计划里面的那个用例树有无法点击，点击就报错，如下：
![cf4ef87ddae956d9e4a3a9fec902fa0](https://user-images.githubusercontent.com/35160325/200168028-8021b176-c434-419f-b22e-dd127a8219ff.jpg)

**Comment by wuranxu** [comment]
已升级umi antd
